# - TRY TO FIND THE LOGGER LIBRARY
# ONCE DONE THIS WILL DEFINE
#
#  LOGGER - SYSTEM HAS LOGGER
#  LOGGER_INCLUDE_DIR - THE LOGGER INCLUDE DIRECTORY
#  LOGGER_LIBRARIES

# IN CACHE ALREADY
IF(LOGGER_INCLUDE_DIR AND LOGGER_LIBRARIES)
    SET(LOGGER_FIND_QUIETLY TRUE)
ENDIF()

FIND_PATH(LOGGER_INCLUDE_DIR
    NAMES
    log.h
    HINTS
    /usr/include
    /usr/local/include
)

FIND_LIBRARY(LOGGER_LIBRARIES
    NAMES
    logger
    liblogger
    HINTS
    /usr/include
    /usr/local/include
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LOGGER
    DEFAULT_MSG LOGGER_LIBRARIES
    LOGGER_INCLUDE_DIR
)
